{"version":3,"sources":["../../src/utils/tryDo_.js"],"names":["exitWithError","require","module","exports","app","action","error","message"],"mappings":";;;;AAAA,MAAMA,aAAa,GAAGC,OAAO,CAAC,wBAAD,CAA7B;;AAEAC,MAAM,CAACC,OAAP,GAAiB,OAAOC,GAAP,EAAYC,MAAZ,KAAuB;AACpC,MAAI;AACA,UAAMA,MAAM,EAAZ;AACH,GAFD,CAEE,OAAOC,KAAP,EAAc;AACZN,IAAAA,aAAa,CAACI,GAAD,EAAME,KAAK,CAACC,OAAN,IAAiBD,KAAvB,CAAb;AACH;AACJ,CAND","sourcesContent":["const exitWithError = require('../utils/exitWithError');\n\nmodule.exports = async (app, action) => {    \n    try {\n        await action();\n    } catch (error) {\n        exitWithError(app, error.message || error);\n    }\n};"],"file":"tryDo_.js"}